### ISSUE TITLE
Enhancement Suggestion: Add Markdown Files for Improved Readability

### ISSUE THREAD

**Issue by JavaBaz** [mmahdi-farrokhy/CleanCodeBook#1]
Hi there!

I've been going through the PDFs from the Clean Code book in the repository, and while the content is fantastic, I believe we can enhance the readability by including corresponding Markdown files.

Markdown files can significantly improve the user experience in the following ways:
1. **Accessibility**: Markdown files can be easier to navigate and read directly within the repository without requiring a separate viewer.
2. **Quick Reference**: They offer a quicker way for developers to scan through sections compared to PDFs.
3. **Searchability and Navigation**: Markdown enables quicker navigation through sections, aiding users in finding relevant content faster compared to PDFs.
4. **Version Control**: Markdown files are text-based, making it easier to track changes using version control systems like Git.

Would it be possible to add Markdown versions alongside the PDFs? This addition could provide a more accessible and user-friendly experience for everyone accessing the repository.

Thanks!

**Comment by mmahdi-farrokhy** [comment]
Hello and thank you for your feedback.
Sure, using markdown files could be a more friendly way to transfer the knowledge and have a more comfirtable experience.
I will add the files asap.

**Comment by mmahdi-farrokhy** [comment]
> Hi there!
> 
> I've been going through the PDFs from the Clean Code book in the repository, and while the content is fantastic, I believe we can enhance the readability by including corresponding Markdown files.
> 
> Markdown files can significantly improve the user experience in the following ways:
> 
> 1. **Accessibility**: Markdown files can be easier to navigate and read directly within the repository without requiring a separate viewer.
> 2. **Quick Reference**: They offer a quicker way for developers to scan through sections compared to PDFs.
> 3. **Searchability and Navigation**: Markdown enables quicker navigation through sections, aiding users in finding relevant content faster compared to PDFs.
> 4. **Version Control**: Markdown files are text-based, making it easier to track changes using version control systems like Git.
> 
> Would it be possible to add Markdown versions alongside the PDFs? This addition could provide a more accessible and user-friendly experience for everyone accessing the repository.
> 
> Thanks!

Hello and thank you for your feedback.
Sure, using markdown files could be a more friendly way to transfer the knowledge and have a more comfortable experience.
I will add the files asap.
